"""Tests for Editor Agent."""
from __future__ import annotations

import pytest
from unittest.mock import patch, MagicMock
from datetime import datetime

from radar.agents.editor import EditorAgent


class TestEditorAgentPromptBuilding:
    """Tests for Editor Agent prompt building."""
    
    def test_build_intel_prompt_empty(self, mock_config):
        """Test prompt building with no intel."""
        agent = EditorAgent()
        
        prompt = agent._build_intel_prompt([])
        
        assert "No significant intel" in prompt
    
    def test_build_intel_prompt_with_items(self, mock_config):
        """Test prompt building with intel items."""
        agent = EditorAgent()
        
        intel_items = [
            {
                "id": 1,
                "competitor_id": "netflix",
                "category": "product",
                "impact_score": 8.0,
                "relevance_score": 7.0,
                "title": "Netflix Feature Launch",
                "summary": "Netflix launched a new feature",
                "annotations": [],
            }
        ]
        
        prompt = agent._build_intel_prompt(intel_items)
        
        assert "Intel #1" in prompt
        assert "netflix" in prompt
        assert "Netflix Feature Launch" in prompt
    
    def test_build_intel_prompt_with_annotations(self, mock_config):
        """Test prompt building with annotations."""
        agent = EditorAgent()
        
        intel_items = [
            {
                "id": 1,
                "competitor_id": "netflix",
                "category": "product",
                "impact_score": 8.0,
                "relevance_score": 7.0,
                "title": "Netflix Feature",
                "summary": "Summary",
                "annotations": [
                    {
                        "agent_role": "product_agent",
                        "priority": "P1",
                        "so_what": "This matters for Tubi",
                        "suggested_action": "Monitor closely",
                    }
                ],
            }
        ]
        
        prompt = agent._build_intel_prompt(intel_items)
        
        assert "Agent Perspectives" in prompt
        assert "product_agent" in prompt
        assert "P1" in prompt
        assert "This matters for Tubi" in prompt


class TestEditorAgentReportGeneration:
    """Tests for report generation."""
    
    @patch.object(EditorAgent, "get_llm")
    def test_generate_report_empty_intel(self, mock_get_llm, mock_config):
        """Test report generation with no intel."""
        agent = EditorAgent()
        
        report = agent._generate_report_markdown([])
        
        assert "No significant competitive intelligence" in report
        mock_get_llm.assert_not_called()
    
    @patch.object(EditorAgent, "get_llm")
    def test_generate_report_with_intel(self, mock_get_llm, mock_config):
        """Test report generation with intel."""
        mock_llm = MagicMock()
        mock_llm.invoke.return_value = MagicMock(
            content="# Tubi Radar Report\n\n## Top Moves\n- Netflix launched feature\n"
        )
        mock_get_llm.return_value = mock_llm
        
        agent = EditorAgent()
        intel_items = [
            {
                "id": 1,
                "competitor_id": "netflix",
                "category": "product",
                "impact_score": 8.0,
                "relevance_score": 7.0,
                "title": "Netflix Feature",
                "summary": "Summary",
                "annotations": [],
            }
        ]
        
        report = agent._generate_report_markdown(intel_items)
        
        assert "# Tubi Radar" in report
        assert "Report generated by Tubi Radar" in report
    
    @patch.object(EditorAgent, "get_llm")
    def test_generate_report_llm_error(self, mock_get_llm, mock_config):
        """Test report generation with LLM error."""
        mock_llm = MagicMock()
        mock_llm.invoke.side_effect = Exception("LLM error")
        mock_get_llm.return_value = mock_llm
        
        agent = EditorAgent()
        intel_items = [{"id": 1, "competitor_id": "test", "category": "product",
                        "impact_score": 5, "relevance_score": 5, "title": "Test",
                        "summary": "Test", "annotations": []}]
        
        report = agent._generate_report_markdown(intel_items)
        
        assert "Error" in report or "Failed" in report


class TestEditorAgentRun:
    """Tests for Editor Agent run method."""
    
    @patch("radar.agents.editor.get_all_intel_for_run")
    @patch("radar.agents.editor.create_report_file")
    @patch.object(EditorAgent, "_generate_report_markdown")
    def test_run_success(
        self, mock_generate, mock_create_file, mock_get_intel, mock_config
    ):
        """Test successful run."""
        mock_get_intel.return_value = [
            {
                "id": 1,
                "competitor_id": "netflix",
                "category": "product",
                "impact_score": 8.0,
                "relevance_score": 7.0,
                "title": "Test",
                "summary": "Summary",
                "annotations": [],
            }
        ]
        mock_generate.return_value = "# Report\n\nContent"
        mock_create_file.invoke.return_value = "/reports/test.md"
        
        agent = EditorAgent()
        result = agent.run(run_id=1)
        
        assert result["intel_items_included"] == 1
        assert result["report_path"] == "/reports/test.md"
    
    @patch("radar.agents.editor.get_all_intel_for_run")
    @patch("radar.agents.editor.create_report_file")
    @patch.object(EditorAgent, "_generate_report_markdown")
    def test_run_respects_max_items(
        self, mock_generate, mock_create_file, mock_get_intel, mock_config
    ):
        """Test that run respects max_report_items config."""
        # Return more items than max
        mock_get_intel.return_value = [
            {"id": i, "competitor_id": "test", "category": "product",
             "impact_score": 5, "relevance_score": 5, "title": f"Test {i}",
             "summary": "Summary", "annotations": []}
            for i in range(50)
        ]
        mock_generate.return_value = "# Report"
        mock_create_file.invoke.return_value = "/reports/test.md"
        
        agent = EditorAgent()
        result = agent.run(run_id=1)
        
        # Should be limited by config.max_report_items (default 20)
        assert result["intel_items_included"] <= 20
    
    @patch("radar.agents.editor.get_all_intel_for_run")
    @patch("radar.agents.editor.create_report_file")
    def test_run_empty_intel(self, mock_create_file, mock_get_intel, mock_config):
        """Test run with no intel."""
        mock_get_intel.return_value = []
        mock_create_file.invoke.return_value = "/reports/empty.md"
        
        agent = EditorAgent()
        result = agent.run(run_id=1)
        
        assert result["intel_items_included"] == 0


class TestEditorAgentConfig:
    """Tests for Editor Agent configuration."""
    
    def test_agent_role(self, mock_config):
        """Test agent role is set correctly."""
        agent = EditorAgent()
        
        assert agent.agent_role == "editor_agent"
    
    def test_temperature_override(self, mock_config):
        """Test temperature can be overridden."""
        agent = EditorAgent(temperature_override=0.5)
        
        assert agent.temperature == 0.5

