"""
Editor Agent (Executive Synthesizer) for Tubi Radar.

Produces a clean, actionable executive brief - not verbose analysis.
"""
from __future__ import annotations

from datetime import datetime
from typing import Optional

from langchain_core.messages import SystemMessage, HumanMessage

from radar.agents.base import BaseAgent
from radar.config import get_config
from radar.tools.db_tools import get_all_intel_for_run, create_report_file


class EditorAgent(BaseAgent):
    """
    The Editor Agent synthesizes intel into a concise executive brief.
    
    Output format:
    1. Executive Summary (3-5 bullet points of what matters)
    2. Key Moves by competitor
    3. Quick take on implications
    
    NO verbose "so what for Tubi" on every item - just the facts and one final synthesis.
    """
    
    agent_role = "editor_agent"
    system_prompt = """You are an executive intelligence briefer for Tubi, a leading free ad-supported streaming service.

Your audience: Senior executives who need the bottom line in 2 minutes.

## OUTPUT FORMAT

Create a clean, scannable brief with this structure:

### EXECUTIVE SUMMARY
3-5 bullet points of the most important things that happened. Lead with the headline, not the analysis.

### KEY MOVES
Group by competitor. For each item:
- **[Competitor]**: What they did (one line)

Only include genuinely significant moves. Skip the noise.

### WATCH LIST
2-3 things to monitor going forward (optional, only if there are clear trends).

## RULES
1. BE CONCISE - executives skim, they don't read essays
2. LEAD WITH FACTS - what happened, who did it, when
3. NO FILLER - skip "this is important because..." just state what matters
4. NO REPETITION - each point once, grouped logically
5. PRIORITIZE - most important first
6. SKIP THE OBVIOUS - don't explain what Netflix is

Write like a Bloomberg terminal alert, not a strategy memo."""

    @property
    def temperature(self) -> float:
        """Use moderate temperature for report writing."""
        if self._temperature_override is not None:
            return self._temperature_override
        return 0.3
    
    def _build_intel_prompt(self, intel_items: list[dict]) -> str:
        """Build the prompt with intel data."""
        if not intel_items:
            return "No significant intel to report."
        
        lines = [f"Date: {datetime.utcnow().strftime('%B %d, %Y')}\n"]
        lines.append(f"Intel items to synthesize: {len(intel_items)}\n")
        
        # Group by competitor
        by_competitor = {}
        for item in intel_items:
            comp = item['competitor_id']
            if comp not in by_competitor:
                by_competitor[comp] = []
            by_competitor[comp].append(item)
        
        for comp, items in sorted(by_competitor.items()):
            lines.append(f"\n## {comp.upper()}")
            for item in items:
                impact = item['impact_score']
                relevance = item['relevance_score']
                lines.append(f"- [{item['category']}] (Impact: {impact}, Relevance: {relevance})")
                lines.append(f"  Title: {item['title']}")
                lines.append(f"  Summary: {item['summary']}")
        
        lines.append("\n---\nSynthesize into a concise executive brief.")
        return "\n".join(lines)
    
    def _generate_report_markdown(self, intel_items: list[dict]) -> str:
        """
        Generate the report using the LLM.
        
        Args:
            intel_items: List of intel dictionaries
        
        Returns:
            Markdown report content
        """
        date_str = datetime.utcnow().strftime("%Y-%m-%d")
        date_full = datetime.utcnow().strftime("%B %d, %Y")
        
        # Handle empty case
        if not intel_items:
            return f"""# Tubi Radar Brief — {date_full}

## Executive Summary

No significant competitive moves detected in this period.

---
*Generated by Tubi Radar*
"""
        
        llm = self.get_llm()
        
        messages = [
            SystemMessage(content=self.system_prompt),
            HumanMessage(content=self._build_intel_prompt(intel_items)),
        ]
        
        try:
            response = llm.invoke(messages)
            report_content = response.content
            
            # Ensure proper header
            if not report_content.strip().startswith("#"):
                report_content = f"# Tubi Radar Brief — {date_full}\n\n{report_content}"
            else:
                # Replace any existing title with our standard format
                lines = report_content.split('\n')
                if lines[0].startswith('# '):
                    lines[0] = f"# Tubi Radar Brief — {date_full}"
                report_content = '\n'.join(lines)
            
            # Add footer
            report_content += f"\n\n---\n*Generated {date_str} by Tubi Radar*\n"
            
            return report_content
        except Exception as e:
            print(f"[EditorAgent] Error generating report: {e}")
            return f"""# Tubi Radar Brief — {date_full}

## Error

Failed to generate report: {str(e)}

---
*Generated by Tubi Radar*
"""
    
    def run(
        self,
        run_id: int,
        min_relevance: Optional[float] = None,
        min_impact: Optional[float] = None,
    ) -> dict:
        """
        Execute the report generation process.
        
        Args:
            run_id: The current run ID
            min_relevance: Minimum relevance score (uses config default if None)
            min_impact: Minimum impact score (uses config default if None)
        
        Returns:
            Dictionary with report generation results
        """
        config = get_config()
        
        # Use lower thresholds to capture more data
        min_relevance = min_relevance or 4.0
        min_impact = min_impact or 4.0
        
        # Get all qualifying intel
        intel_items = get_all_intel_for_run(
            run_id=run_id,
            min_relevance=min_relevance,
            min_impact=min_impact,
        )
        
        # Sort by impact, take top items
        intel_items = sorted(intel_items, key=lambda x: x['impact_score'], reverse=True)
        intel_items = intel_items[:30]  # More items for better synthesis
        
        print(f"[EditorAgent] Generating brief from {len(intel_items)} intel items...")
        
        # Generate report
        report_markdown = self._generate_report_markdown(intel_items)
        
        # Save report
        report_path = create_report_file.invoke({
            "run_id": run_id,
            "content_markdown": report_markdown,
        })
        
        print(f"[EditorAgent] Report saved to: {report_path}")
        
        return {
            "intel_items_included": len(intel_items),
            "report_path": report_path,
            "report_length": len(report_markdown),
        }


def run_editor(run_id: int) -> dict:
    """
    Convenience function to run the Editor Agent.
    
    Args:
        run_id: The current run ID
    
    Returns:
        Editor results
    """
    agent = EditorAgent()
    return agent.run(run_id=run_id)
